server:
  port: 8900


a2a4j:
  host:
    # global notification
    notification:
      url: http://127.0.0.1:8989/notify

    agents:
      echoAgent:
        baseUrl: http://127.0.0.1:8901
        #notification:
        #  url: http://127.0.0.1:8989/notify

logging:
  level:
    io.github.pheonixhkbxoic.a2a4j: debug