server:
  port: 8903

logging:
  level:
    io.github.pheonixhkbxoic.a2a4j: debug

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0